server:
  protocol: http
  address: 127.0.0.1 #server ip address
  port:  9008 #该模块提供服务的端口（必须）
  url: http://127.0.0.1:8088/dss/visualis #frontend index page full path
  access:
    address: 127.0.0.1 #frontend address
    port: 8088 #frontend port

#指定eureka Server的地址，用于注册（必须）
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere
#（必须）
management:
  endpoints:
    web:
      exposure:
        include: refresh,info

logging:
  config: classpath:log4j2.xml

file:
  userfiles-path: ${DAVINCI3_HOME}/userfiles
  web_resources: ${DAVINCI3_HOME}/davinci-ui/
  phantomJs-path: ${DAVINCI3_HOME}/bin/phantom.js
  base-path: ${DAVINCI3_HOME}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: visualis-dev #模块名，用于做高可用（必须）
  ## davinci datasouce config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dss?characterEncoding=UTF-8&allowMultiQueries=true
    username: hadoop
    password: hadoop
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10
    type: com.alibaba.druid.pool.DruidDataSource
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat
    break-after-acquire-failure: true
    connection-error-retry-attempts: 3
    validation-query: SELECT 1
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
      enabled: true
      location: /

  config:
    location: classpath:/
    additional-location: file:${DAVINCI3_HOME}/conf/
    name: application

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, file:${file.userfiles-path}, file:${file.web_resources}

  mvc:
    static-path-pattern: /**


  thymeleaf:
    mode: HTML5
    cache: true
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cache:
    caffeine:
      type: caffeine
  mail:
    host: 127.0.0.1
    port: 8000
    username: wedatasphere
    password: wedatasphere
    nickname: wedatasphere

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: false

springfox:
  documentation:
    swagger:
      v2:
        path: /api-doc


pagehelper:
  supportMethodsArguments: true
  reasonable: true
  returnPageInfo: check
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: edp.davinci.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

mapper:
  identity: MYSQL
  not-empty: false
  mappers: edp.davinci.dao

sql_template_delimiter: $

custom-datasource-driver-path: ${DAVINCI3_HOME}/conf/datasource_driver.yml

phantomjs_home: ${DAVINCI3_HOME}/bin/phantomjs

email:
  suffix: ""
screenshot:
  default_browser: PHANTOMJS                    # PHANTOMJS or CHROME
  timeout_second: 1800
  phantomjs_path: ${DAVINCI3_HOME}/bin/phantomjs
  chromedriver_path: $your_chromedriver_path$

